Hello Microverse project pull request
eyoab01/Project1-repo-main pull request #2
Opened 2022-08-18 14:11 UTC by eyoab01

2022-08-18 14:18 UTC, aimemalaika requested changes
Hi @eyoab01 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

- [ ] Kindly. add linters configuration to your repo
- [ ] Kindly use the CSS file to style the header
- [ ] Kindly add a description to your pull request

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 14:18 UTC, aimemalaika commented on test.md
> +This file should be ignored by git
- [ ] Kindly include the test.MD in the git ignore file so that it won't be deployed to the repository
- [ ] Kindly add a .gitignore file to your project

2022-08-19 07:26 UTC, eyoab01 commented on test.md
> +This file should be ignored by git
i changed acordingly

2022-08-19 08:13 UTC, BenMukebo requested changes
### Hi @eyoab01,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Read
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] As requested by the previous reviewer, Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=basic%20rules%20to%20follow%20in%20Microverse%20projects)
eg: 
```
## In this Milestone, I have done the following step to set up a "Hello world" repository:

- [ ] Create a new GitHub repo.
- [ ] Add a `.gitignore` file.
- [ ] Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config).
- [ ] Make sure that any files that are not relevant are ignored by git.
- [ ] Add a descriptive README file ....

```


- [ ]  As requested by the previous reviewer, According to the project requirements, There is a .gitignore file listing test.md file and node_modules directory. Kindly ensure you have the `.gitignore` file that ignores your `test. md` file and the  `node_modules` directory. Address this ✍🏻 

- [ ]  As requested by the previous reviewer, Please kindly update your `readme file` to reflect the changes for this milestone as this will make your `readme file` more informative and professional. Check out this [template](https://github.com/microverseinc/readme-template) and adapt it to your project. Replace all the information in the various sections of the template with information pertaining to your project. 

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] You have used different base branch, According to the GitHub flow rule, Your Pull Request should be made from the “feature branch” into the `main` branch. and not the inverse. I strongly suggest you change the base branch using this Github doc -> [Changing the base branch of a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)Pull Request is made from the “feature branch” into the main branch. Note: In cases where students used a different base branch you can suggest they change the base branch using this Github doc -> [Changing the base branch of a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)
### Note: This is only optional because due to oversight the previous reviewer probably missed them. However, it is important.
- [OPTIONAL ] Kindly, make use of descriptive commit messages. Each commit message should be written in the imperative tense and always `capitalized`. [Read more about how to write descriptive commit messages](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Use%20descriptive%20commit%20messages%20%2D%20each%20commit%20should%20be%20small%20enough%20to%20describe%20it%20in%20one%20sentence.%20The%20commit%20message%20should%20be%20written%20in%20the%20imperative%20tense%20and%20capitalized). 
At this moment you are not required to update the Commit messages try to use this rule in your future projects.
Example:
  - :x: Wrong: added Descriptive README
  - :heavy_check_mark: Right: Add descriptive README 
 


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 08:13 UTC, BenMukebo commented on index.html
> +<h1>Hello Microverse!</h1>
- [ ] According to the project requirements 👇🏻, the style.css file should include one class with styles for your header `h1` (make in your favorite color). Kindly add this 

![15](https://user-images.githubusercontent.com/79058364/184992901-0f5bb6a2-14bf-46c2-863b-bef56fe020bc.png)

- This should look like this:
- index.html
 ```html
  <h1 class="header">Hello Microverse!</h1>
```
- style.css
```css
.header {
    background-color: rgb(170, 170, 146);
}
```

2022-08-19 08:13 UTC, BenMukebo commented on README.md
> +> Microverse Project1
- [ ]  Please, add a meaningful  `Project description`. Remember A project description is a high-level overview of why you're doing a project. The document explains a project's objectives and essential qualities. Is an essential document that provides your audience with a comprehensive overview of the project. Think of it as the elevator pitch that focuses on what and why without delving into how. 😉 💯

2022-08-19 08:13 UTC, BenMukebo commented on README.md
>  ## Live Demo (if available)
- [ ] - [OPTIONAL] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd project_name`, etc 🙃 

- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

2022-08-19 08:13 UTC, BenMukebo commented on index.html
> +<head>
- [OPTIONAL] You should have the `link` tag inside your `head` tag container in order to link your index.html file with the style.css file, Actually, there is no connection between them, the index.html file can't recognize where your CSS file is exactly located. In order to solve this, you need to add this line after line 6 inside the index.html.  this should be like that:
 ` <link rel="stylesheet" href="./styles.css">`


### This is only optional because due to oversight the previous reviewer probably missed them. However, it is important.

2022-08-19 08:13 UTC, BenMukebo commented on README.md
> -- GitHub: [@githubhandle](https://github.com/githubhandle)
- [ ] This is not a pair programming project, you don't need to have two Authors Kindly remove the  **Author2** from the ## Authors section 🚮 
- [ ] Make sure to remove all unnecessary titles since they are empty (Prerequisites, run tests Deployment ....)
- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

2022-08-19 10:29 UTC, closed without merging